name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Runs once every day at midnight UTC
  workflow_dispatch:     # Allows manual trigger

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: shyamatyagi
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Push to GitHub
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
